- src/components/ContentCard.vue
Fully fix is better patch [likecoin/ui-vue](https://github.com/likecoin/ui-vue), for now this will do
> 🚑 Temp fix for avatar not showing in <ContentCard/>

- .circleci/config.yml
- functions/apiHttp/config/config.js
- src/components/SlidingMenu.vue
- src/layouts/error.vue
- src/mixins/intercom.js
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
- src/pages/civic/payment/paypal/fail.vue
- src/plugins/vue-intercom.js
- src/server/api/routes/users.js
- src/server/config/config.js
- src/store/modules/actions/user.js
Please ignore the google analytics commit from the other PR
> ✨ Add intercom related features

- src/components/ContentCard.vue
- src/components/ContentList.vue
- src/server/api/routes/reader.js
- src/util/api/index.js
TODO: move most logic in client store
>  💩 Fetch content like count in server side

- src/components/ContentCard.vue
- src/components/ContentCardWrapper.vue
🐛 Fix infinite loading on article without content
> 🐛 Fix display name on ContentCard

- src/nuxt.config.js
- src/plugins/client-ui-plugins.js
- src/plugins/ui-plugin.client.js
✨ Attempt to use IntersectionObserver in vue-lazy
> 🎨 Rename client plugin to follow nuxt plugin name conventional

- src/assets/css/_transitions.scss
- src/assets/css/index.scss
- src/components/ContentCard.vue
- src/components/ContentCardWrapper.vue
- src/components/PageHeader.vue
- src/components/SiteNavBar.vue
- src/components/SlidingMenu.vue
- src/components/TabBar.vue
- src/components/TabBarItem.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/sliding-menu.js
- src/pages/index.vue
- src/pages/index/bookmarks.vue
- src/pages/index/following.vue
- src/pages/index/index.vue
Better view with ignore white space option on and commit by commit
> Fixes before launch

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/index/index.vue
> 🚸 Add header label in featured feed

- src/components/AuthorListItem.vue
- src/components/ContentCard.vue
- src/components/SlidingMenu.vue
- src/nuxt.config.js
mostly work in offline mode for now
> ⚡️ Add img/api srcs into workbox caching

- src/constant/index.js
- src/server/api/constant/index.js
- src/server/api/index.js
- src/server/api/routes/users.js
- src/store/index.js
- src/store/modules/actions/reader.js
> ⚡️ Skip store init if no cookie exist

- firebase.json
- functions/ssrapp/index.js
- src/nuxt.config.js
- src/store/index.js
🔊 Add server.timing in dev mode
🐛 Fix hosting was not used for some client asset
🐛 Fix process.env was not apply in nuxt.config
> Fix more config and add server.timing

- src/pages/settings/language.vue
- src/server/api/constant/index.js
https://bugs.webkit.org/show_bug.cgi?id=188165
> 💩 Temp disable samesite lax due to safari12 bug

- functions/package-lock.json
- functions/package.json
- src/assets/css/components/_buttons.scss
- src/components/BaseDialog.vue
- src/components/CollapsibleView.vue
- src/components/DialogContainer.vue
- src/components/FirstTimeSignInDialog.vue
- src/components/LikerComparisonCard.vue
- src/components/WelcomeDialog.vue
- src/layouts/default.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/package-lock.json
- src/package.json
- src/plugins/ui-plugin.client.js
- src/server/api/routes/users.js
- src/util/api/index.js
> Add WelcomeDialog

- src/experiments/civic/index.js
- src/pages/civic/index.vue
Replace https://github.com/likecoin/liker-land/pull/143
> ⚗️ Add direct sign in AB test in /civic

- src/experiments/civic/index.js
- src/layouts/error.vue
- src/locales/zh-Hant.json
- src/nuxt.config.js
> End customized auth error experiment

- src/constant/index.js
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/civic/index.vue
Show Intercom dialog if the third option is clicked
> 🚸 Add other method in Civic Liker payment options

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/civic/index.vue
💬 Change `other` payment method description
> 🚸 Add prefill message for other civic payment method

- src/components/WelcomeDialog.vue
> ✨ Add payment select in Welcome dialog

- src/pages/civic/index.vue
- src/pages/civic/register/other.vue
Reverts likecoin/liker-land#167
> Revert "🚸 Boot intercom when register civic with `other`"

- src/pages/civic/register/other.vue
> 💄 Adjust other payment page layout

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
- src/server/api/routes/civic/stripe.js
- src/server/api/routes/hook/index.js
Reverts likecoin/liker-land#174
> Revert "✨ Support stripe checkout setup mode for existing customer"

- src/experiments/civic/index.js
- src/nuxt.config.js
- src/pages/civic/index.vue
This reverts commit e3667faf1157c8fb63696b70c72f167dceb55798.
> ⏪ Revert "⚗️ Show payment option first in mobile AB test"

- src/plugins/ui-plugin.client.js
AttrPlugin should be already included in core
> 🐛 Fix gsap syntax

- functions/package-lock.json
- functions/package.json
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
still debugging ga not working issue, maybe this will help
> ⬆️ Upgrade analytics package

- functions/package-lock.json
- functions/package.json
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
Reverts likecoin/liker-land#212
> Revert "⬆️ Upgrade analytics package"

- src/experiments/civic/index.js
- src/layouts/error.vue
> ⚗️ Flip experiment variant for test

- src/server/api/routes/civic/stripe.js
should fix https://github.com/likecoin/liker-land/issues/226
> 🐛 Return pas_due stripe info in api

- src/server/api/routes/reader/index.js
- src/server/api/routes/users.js
🐛 Fix did not return after http 400
🐛 Fix toLowerCase() of undefined string
> 🐛 Fix server js errors seen in sentry

- src/pages/civic/payment/paypal/success.vue
- src/server/api/routes/civic/index.js
- src/util/api/index.js
> 🔧 Change paypal config

- src/util/EventLogger.js
unlike google in which value can be any amount, in fb pixel, value must mean $$
> 📈 Remove value from fbq event

- functions/index.js
`FUNCTION_NAME ` was renamed to `K_SERVICE`
> 👽 Fix firebase cloud function changed env name in node10 runtime

- src/server/api/routes/users.js
Current liker.land api includes unused data like civic and superlike status, which we fetch separately in app
I have made a new api that only returns user login status which should improve api speed
> ✨ Add a minimal version of /self api for login check

- src/server/api/routes/reader/index.js
- src/server/api/util/api.js
Deploy after follow data migration is complete
> 🔥 Do not auto add liked user to followed list

- src/server/api/middleware/error.js
- src/server/api/routes/reader/bookmark.js
- src/server/api/routes/reader/follow.js
- src/server/api/routes/reader/index.js
Return original 4xx error back to client
> ♻️ Refactor error handler to allow 4xx error to be emit back

- src/pages/settings/civic.vue
- src/server/api/routes/civic/stripe.js
- src/util/api/index.js
Replaces checkout update billing method url
> ✨ Add stripe billing portal

- functions/package-lock.json
- functions/package.json
- src/components/AppDownloadBadges/AppDownloadBadges.vue
- src/components/CreatorsPage/CreatorsPage.vue
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
I am not sure if preinstall script would work in firebase, would be nice if extract css plugin actually make a release soon
> ⚡️  Various performance improvement

- src/package-lock.json
> ⬇️ Downgrade Vue-Lazyload to 1.2.6

- src/package-lock.json
- src/package.json
This would conflict wit #318 so maybe we should handle either one first
> ⬆️ Upgrade extract-css-chunks-webpack-plugin for css preload

- src/server/api/util/api.js
> 🐛 Fix missing filter params

- src/components/CivicSubscriptionView/CivicSubscriptionView.vue
- src/components/CreatorsPage/sections/Hero/Hero.vue
- src/pages/_id/index.vue
> Update & fix on CL2.0

- src/components/SiteNavBar.vue
- src/locales/index.js
- src/pages/settings/language.vue
- src/plugins/vue-i18n.js
- src/server/api/constant/index.js
- src/server/api/routes/users.js
- src/server/api/util/api.js
- src/store/modules/actions/user.js
- src/util/api/index.js
Depends on https://github.com/likecoin/likecoin-api-public/pull/213
> 🌐 Sync like.co language preferences

- src/assets/icons/alert-circle.svg
- src/assets/icons/cross.svg
- src/components/Button/Button.vue
- src/components/CL1VsCL2Link.vue
- src/components/CivicSettingsV1.vue
- src/components/CivicSubscriptionView/CivicSubscriptionView.vue
- src/components/SiteNavBar.vue
- src/components/SlidingMenu.vue
- src/layouts/error.vue
- src/locales/zh-Hant.json
- src/pages/creators/setup.vue
- src/pages/index.vue
- src/pages/settings/language.vue
- src/plugins/vue-i18n.js
- src/server/api/routes/users.js
- src/server/api/util/api.js
- src/util/api/index.js
Depends on https://github.com/likecoin/like-co/pull/1489
> Fix CL2.0 sub flow

- src/server/api/routes/reader/index.js
This shall prevent the app from crashing until the new app release
> 🚑 Guard malformed SLed content URL

- src/plugins/experiment.client.js
Ref: https://stackoverflow.com/questions/50686295/gtag-js-optmize-server-side-implementation-not-working
Not sure if we should be using variant name or indexes though
> 🐛 Fix experiment plugin code for gtag

- src/server/api/routes/civic/stripe.js
Currently this API throw 500 if someone deleted the customer ID from stripe UI
> 🥅 Handle stripe record error if customer was deleted

- src/components/Card/PureCard.vue
- src/components/CivicLikerPage/sections/BetterWorldSection.vue
- src/components/CivicLikerPage/sections/SuggestedCreatorsSection.vue
- src/components/CivicLikerPitchingView/CivicLikerPitchingView.vue
- src/components/CivicSubscriptionView/CivicSubscriptionView.vue
- src/components/Identity/Identity.avatar.vue
- src/components/Identity/Identity.stories.js
- src/components/Identity/Identity.vue
- src/components/SettingsPageHeader.vue
- src/pages/civic/_from.vue
- src/util/api/index.js
Allow controlling avatar outline extrusion
> Various fixes on /civic and others

- src/.storybook/preview.js
- src/components/Card/Card.stories.js
- src/components/CivicLikerPage/sections/SuggestedCreatorsSection.vue
- src/components/SuperLikeContentGrid.vue
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
- src/pages/_id/index.vue
- src/plugins/vue-stack-grid.client.js
TLDR: Implementation to mimic masonry layout with flexbox and portal
There are many masonry layout implementations, however, many of them are using absolute position in grid items, in addition, they may also require knowing the width and the height of the grid items in advance, or monitoring inner image loading to update position calculation, etc. Absolute position is good for animation, but in some edge cases, it is kind of buggy, as you may have seen overlapping grid items.
It is easy to implement a grid layout with simple CSS but the tricky part is if not all contents are the same height, then the following may happen, notice the red boxes below
And we want this to happen
Portal enables rendering element at arbitrary slot
Using this DOM structure
- Col 1
- Row 1
- Portal 1
- Row 2
- …
> 💩 Rewrite SuperLikeContentGrid implementation using portal

- src/components/SuperLikeContentGrid.vue
Fix item not re-render after items update
> 🚑 Fix Super Like grid item not update

- src/components/AuthorListItem.vue
- src/components/ContentCard.vue
We dont need img in cors mode unless we want to use it in canvas
> 🐛 Remove unneeded crossorigin="anonymous" in <img>

- src/components/Button/Button.vue
- src/components/CivicDashboard.vue
- src/components/CivicLikerPage/sections/SuggestedCreatorsSection.vue
- src/components/CivicLikerWeb3Notice.vue
- src/components/SlidingMenu.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/civic/_from.vue
- src/pages/civic/dashboard.vue
- src/pages/creators/dashboard.vue
- src/pages/creators/index.vue
Waiting for URL of Civic Liker Web 3 announcement article
> 🚧 Add Civic Liker Web 3 Notice UI

- src/components/SlidingMenu.vue
- src/pages/about.vue
> 🔥 Remove About page and related  buttons

- src/mixins/nft.js
Requires https://github.com/likecoin/app-like-co/pull/178
> 🔥 Remove /1 hack for iscn display

- src/nuxt.config.js
Actually I am not sure which dependency trigger wasm csp
> 🔒️ Allow wasm-eval

- src/mixins/nft.js
- src/pages/nft/class/_classId.vue
Fetch metadata in the server side for OG display properly
> 🐛 [Details Page] Fix OG issues

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
This allow dev on m1 + node@14 without nvm/zsh
> ⬆️ Upgrade node-sass@5 to remove python2

- src/components/NFTCampaign/Item.vue
- src/components/NFTCampaign/ItemBase.vue
- src/components/NFTWidget/ContentPreview.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> 🚸 [NFT Widget] Swap content & details click zone

- src/components/AboutNFTPage/index.vue
- src/components/NFTCampaign/Item.vue
- src/components/NFTCampaign/ItemBase.vue
- src/components/NFTPortfolio/Card.vue
- src/components/NFTPortfolio/Item.vue
- src/mixins/nft.js
- src/pages/_id/index.vue
- src/pages/nft/class/_classId.vue
Also refactorized portfolio UI
> Add analytics event

- src/components/NFTCampaign/Item.vue
- src/components/NFTPortfolio/Item.vue
- src/mixins/nft.js
> Fix layout & warning

- src/components/NFTPortfolio/Item.vue
- src/mixins/nft.js
Need to filter out NFTs that are not Writing-NFTs
> 🐛 [Details] Display only Writing NFT

- src/server/api/util/api.js
> ✨ Move try to handle doc.get

- src/components/NFTPage/CollectorList/index.vue
- src/components/NFTPage/EventList/index.vue
- src/components/ShowMore.vue
- src/pages/nft/class/_classId.vue
- src/tailwind.config.js
> 📱 [Details] Adjust Dialog layout

- src/components/NFTPage/SupplySection.vue
- src/components/NFTSupply/Row.vue
- src/components/NFTSupply/Table.vue
> Adjustment for NFTSupplyTable

- src/components/Menu.vue
> 💄 Update Menu divide color

- src/components/AboutNFTPage/index.vue
- src/components/Menu.vue
- src/components/MenuIcon.vue
- src/components/SiteHeader.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/wallet.js
- src/tailwind.config.js
> 💄 Update main menu UI & label

- functions/package-lock.json
- functions/package.json
- src/constant/network.js
- src/package-lock.json
- src/package.json
- Disable Keplr Mobile for now (Not supported collect)
- Support Direct Signer with Liker Land app (@likecoin/wallet-connector@0.10.0-alpha)
> Improve mobile experience

- src/constant/index.js
https://liker.land/nft/class/likenft1faqzun5eucvh07j0fnrk7wehs966y32wujxrfuvlkzwdyfg03h6qnrscau
> 🔧 [Campaign] Update listing

- src/components/NFTWidget/ContentPreview.vue
- src/tailwind.config.js
> 💄 [NFT Widget] Clamp title & description

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/class/_classId.vue
https://user-images.githubusercontent.com/75730405/188051304-6687265a-62f5-409d-ab61-046698df282d.mov
> ✨ [Details] Add query string to trigger collecting flow

- src/components/NFTAboutPage/CTASection.vue
♻️ Use click methods for logTracker
Want to confirm that the Legacy event is mentioned here, do you think there is no need to add an event?
> ♻️ Use click methods for logTracker

- src/components/NFTPortfolio/Item.vue
> ♻️ Use click.native

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
- src/store/modules/actions/wallet.js
> 🐛 Fix params for removing session listener

- src/components/ButtonV2.vue
- src/components/NFTPage/PriceSection.vue
- src/pages/nft/class/_classId/index.vue
> 📈 Add event sell button

- src/mixins/nft.js
- src/util/nft.js
✨ Split sign broadcast in collect
> ✨ Split sign broadcast in collect

- src/mixins/nft.js
- src/util/nft.js
Take [the genesis NFT](https://liker.land/nft/class/likenft1yhsps5l8tmeuy9y7k0rjpx97cl67cjkjnzkycecw5xrvjjp6c5yqz0ttmc) for example:
before:
after:
> ✨ Merge NFT events in DB into on-chain events

- src/mixins/nft.js
- src/util/api/index.js
Needed for https://github.com/likecoin/likecoin-api-public/pull/348
> 👽️ Add class_id in transfer api

- src/mixins/nft.js
- src/util/EventLogger.js
📈 Add collect event add_to_cart
> 📈 Add collect event add_to_cart

- src/nuxt.config.js
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/class/_classId/share/index.vue
https://developers.google.com/search/docs/advanced/structured-data/product
Moved `fetchNFTPurchaseInfo` to `fetch` to allow using price in SSR
> 🔍️ Add product json ld for writing nft

- src/mixins/nft.js
> 🐛 Fix unable to transfer after first collect

- src/mixins/nft.js
defer runs the script after dom is ready, async run as soon as it is loaded
> ⚡️ Lower stripe script priority

- src/constant/index.js
- src/pages/nft/class/_classId/index.vue
we need usd for it to be valid so a rough estimation
> 🔍️ Fix product json ld

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
> 🐛 Fix Cosmostation extension connect

- .circleci/config.yml
- firebase.json
- functions/apiHttp/index.js
- functions/backupCron/index.js
- functions/package-lock.json
- functions/package.json
- functions/ssrapp/index.js
us-west should get us lower latency than us-central(default)
sad that us-west1 is not availble for firebase functions
> ⚡️ Move to us-west2

- src/util/api/index.js
Should be reverted when solving conflict...
> 🐛 [Civic] Fix status fetching

- src/components/CivicLikerV3/Dashboard.vue
- src/components/SiteHeader.vue
- src/util/links.js
Requires https://github.com/likecoin/like-co/pull/1665
> 🚸 Use popup for settings

- firebase.json
- functions/.env.civic-liker
- functions/.env.civic-liker-develop
- functions/apiHttp/config/config.js
- functions/apiHttp/index.js
- functions/package.json
- functions/ssrapp/index.js
- src/server/api/util/api.js
Only upgrade ssrapp function and its config to solve page response time issue
Will handle api upgrade later
> ⬆️ Use firebase fn v2 for ssrapp

- src/components/EventModal/Collect/index.vue
- src/mixins/clipboard.js
- src/mixins/portfolio.js
- src/pages/nft/class/_classId/index.vue
> ✨ Use Web Share API for sharing URL

- src/mixins/clipboard.js
> ♻️ Remove share function

- firebase.json
- functions/.env.civic-liker
- functions/.env.civic-liker-develop
- functions/apiHttp/config/config.js
- functions/apiHttp/index.js
- functions/package.json
- functions/ssrapp/index.js
- src/server/api/util/api.js
API_URL is not used anyway in code, but is used by @nuxtjs/axios for firing xhr from frontend
> 🚑️ Fix missing API_URL env

- src/components/CivicLikerV3/Dashboard.vue
- src/components/SiteHeader.vue
- src/locales/zh-Hant.json
- src/mixins/wallet.js
- src/pages/settings/index.vue
- src/util/links.js
Requires https://github.com/likecoin/like-co/pull/1668
> Update settings page & Liker ID settings 

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
https://github.com/likecoin/likecoin-wallet-connector/pull/11/files/d6bc5535682758b5d318b7e6ed3a807ec7050540..70a853d744a0ba3ac3cf13254b96c56b0f259412
> ⬆️ Upgrade @likecoin/wallet-connector to v0.16.0-beta.2

- src/components/CivicLikerV3/PureDashboard.vue
- src/components/Identity/Identity.vue
- src/components/NFTPortfolio/Base.vue
- src/components/NFTWidget/ContentPreview.vue
- src/components/NFTWidget/LikeActionBar.vue
- src/pages/campaign/writing-nft.vue
Improve loading speed for front page, nft cards related page, and civic
> ⚡️ Lazy loading on nft cards and below the fold image

- firebase.json
- functions/.env.civic-liker
- functions/.env.civic-liker-develop
- functions/apiHttp/config/config.js
- functions/apiHttp/index.js
- functions/backupCron/index.js
Migrate function config to env files and secret manager
Use v2 syntax
> ♻️ Migrate api to fn v2 and secret

- .circleci/config.yml
- firebase.json
- functions/package-lock.json
- functions/package.json
- src/config/sitemap.js
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
- src/util/api/index.js
This PR adds sitemap module, and adds a function that fetches nft classes from highest rank and latest, then list them in sitemap.xml
> ✨ Add sitemap for nft classes

- src/components/NFTPage/CollectorList/Items.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/util/api/index.js
> 💄 Add avatar to collector list

- src/config/sitemap.js
Temp solution: add some creator owned by api wallet to sitemap
we should be using creator and collector api in the future to obtain wallets
> ✨ Add userId to sitemap

- src/store/modules/actions/wallet.js
- src/util/EventLogger.js
should be in object instead of string...
> 📈 Fix invalid setUser and add login event

- src/components/NFTGem/Wrapper.vue
- src/components/NFTGem/index.vue
- src/components/NFTPage/PriceSection.vue
- src/pages/nft/class/_classId/index.vue
hover only shows for img `title`
using `.once` should be enough for firing analytics event once
> 📈 Add gem hover title and event, simplify sell event

- src/mixins/nft.js
- src/util/api/index.js
- src/util/nft.js
✨ get event only msg type, no need filter
> ✨ get event only msg type, no need filter

- src/mixins/nft.js
- src/util/api/index.js
> ✨ Add ignoreToList in event

- src/util/EventLogger.js
https://developers.google.com/analytics/devguides/collection/ga4/reference/events#purchase
currency is required
> 🐛 Fix missing currency in purchase event

- src/components/Footer.vue
- src/mixins/crisp.js
- src/mixins/nft.js
> 🚸 Show Crisp for all NFT related page

- src/pages/nft/class/_classId/index.vue
[Error Example](https://liker.land/nft/class/likenft1e59axcl5f32adr2tdr4wka9ercd3qpcgwspasjdq7v7zt5pjwd5s4e5x9)
> 🐛 Fix unhandled NFT not found error

- src/components/Identity/Identity.avatar.vue
- src/components/NFTPage/PreviewCard.vue
- src/components/NFTPortfolio/Base.vue
- src/components/NFTWidget/ContentPreview.vue
- src/util/ui.js
Requires https://github.com/likecoin/likecoin-api-public/pull/384
> ⚡️ Use resized nft image url

- src/components/NFTPage/ControlBar.vue
Usage
UI
- `oweCount && ownNftIds.includes(currentNftId) && view !== 'created'`
- `!oweCount || view === 'created'`
> 💄 Add control bar component

- src/components/NFTPage/EventList/Metadata.vue
- src/components/NFTPage/EventList/index.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/class/_classId/index.vue
- Collected view
- Created view
> 💄[Details] Update event list UI

- src/store/modules/actions/user.js
- src/util/EventLogger.js
Seems crisp is throwing errors, remove crisp event calls for now since we don't really has user id for now
> 🔥 Remove crisp events

- src/util/nft.js
> 🚑 Fix W.NFT checking

- src/components/CivicLikerV3/PureDashboard.vue
- src/components/CivicLikerWeb3Notice.vue
- src/components/CommunityCTA/CommunityCTA.vue
- src/components/LinkV2.vue
- src/components/NFTAboutPage/index.vue
- src/components/NFTCampaign/ItemBase.vue
- src/components/SiteHeader.vue
We actually want to know internally the referrer and let creators know likerland traffic
> 📈 Remove no referrer for internal and article links

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/campaign/writing-nft.vue
> ✨ Add link to nft dashboard

- src/components/NFTPortfolio/UserInfo.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/portfolio.js
- src/mixins/wallet.js
- src/pages/_id/index.vue
- src/pages/dashboard/index.vue
- src/store/modules/actions/staticData.js
- src/util/api/index.js
Seems `head()` inside mixin is troublesome
> 🐛 Fix portfolio & dashboard OG

- src/components/NFTCampaign/Item.vue
- src/components/NFTMessage/index.vue
- src/components/NFTPortfolio/Item.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/pages/nft/class/_classId/_nftId.vue
> ✨ Implement new NFT details page

- src/components/NFTPage/ControlBar.vue
> 🐛 Fix collect button not showing in <ControlBar/>

- src/mixins/nft.js
- src/util/nft.js
- https://github.com/likecoin/liker-land/pull/797 
- https://github.com/likecoin/likecoin-api-public/pull/399
> 🥅 Detect failed Tx

- src/components/NFTPortfolio/Card.vue
> 💄 [Dashboard] Update the wrapper style of hidden item

- src/components/NFTPortfolio/UserInfo.vue
- src/components/ToolTips.vue
- src/pages/_id/index.vue
- src/util/ui.js
> ✨ [Portfolio] Enable copy address

- src/components/NFTPortfolio/MainView.vue
- src/store/modules/nft.js
- src/util/nft.js
https://user-images.githubusercontent.com/17264716/205434571-31cb2c3b-f04c-4cc1-8641-3e7c2a0b156d.mov
https://user-images.githubusercontent.com/17264716/205434576-9b3894cc-6f73-4fef-a62c-6a83ec9246d6.mov
> 💄 [Portfolio] Mitigate items flashing when loading

- src/components/NFTCampaign/ItemBase.vue
> 💄 Use imgBgColor for campaign item hover effect

- src/components/EventModal/Transfer.vue
I am not sure if @once work on Textfield yet, testing
> 📈 Add transfer message event

- src/mixins/nft.js
- src/util/api/index.js
ts was missing when migrating purchase api to liker.land
> 🐛 Add missing ts in purchase api call

- src/components/NFTPortfolio/ItemPlaceholder.vue
- src/components/NFTPortfolio/MainView.vue
https://user-images.githubusercontent.com/17264716/207571057-bf21aa0a-9d21-400f-b1b7-16928296ef2b.mov
> 🐛 Fix layout glitch & improve loading indictor

- src/mixins/nft.js
> 🚑️ Fix invalid ISCN ID field

- src/components/NFTPage/EventList/Table.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
TODO: fetch price from TX data
> 💩 Rough support for buy_nft events

- src/pages/nft/class/_classId/_nftId.vue
> 🐛 [_nftId/] Fix missing collectedCount & collectorCount

- src/components/NFTGem/index.vue
> 🚸 Use tooltip for gem names

- src/components/Identity/Identity.avatar.vue
- src/components/NFTPortfolio/TopUsersList.vue
- src/components/NFTPortfolio/UserInfo.vue
- src/store/modules/nft.js
Before
After
Before
After 
Added hover effect
https://user-images.githubusercontent.com/17264716/209224064-03a39868-edce-4970-8d19-447b2e78d099.mov
Before
After
Before
After
> Various fix & improvements

- functions/firestore/index.js
- functions/modules/misc.js
- functions/package-lock.json
- functions/package.json
- functions/pubsub/index.js
- src/components/NFTPortfolio/SubscriptionForm.vue
- src/server/api/routes/nft/mint-subscription.js
- src/util/api/index.js
Requires https://github.com/likecoin/likecoin-edm/pull/32
> 🌐 [Creator Follow] Keep language of submit form & confirmation page consistence

- src/components/CivicLikerV3/PureDashboard.vue
> 🚸 Move connect wallet and register button up to step 1 in civic page

- src/components/NFTMessage/index.vue
- src/locales/en.json
> 🚸 Show message hint even for single message

- src/components/NFTGem/Wrapper.vue
- src/components/NFTPortfolio/Base.vue
- src/components/NFTPortfolio/Item.vue
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/store/modules/nft.js
- src/util/writing-nft.js
Fix gem level logic, should only count purchase count
> ♻️ Refactor gem level logic to store

- src/components/EventModal/Collect/index.vue
- src/components/Icon/Input.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/util/nft.js
> 💄 Add input for collector's message

- src/components/UserStats/Gem.vue
- src/pages/_id/index.vue
- src/util/writing-nft.js
> 💄 Add gem list in user stat

- src/components/NFTPortfolio/UserInfo.vue
- src/pages/_id/index.vue
> 💄 Put gem list above user description

- src/components/Footer.vue
- src/components/MenuIcon.vue
- src/components/SiteHeader.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> ✨ Add mint nft button in menu and footer

- src/components/NFTAboutPage/CTASection.vue
- src/components/NFTAboutPage/index.vue
- src/components/NFTCampaign/ItemBase.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/campaign/writing-nft.vue
- src/pages/index.vue
- src/pages/writing-nft/about.vue
- src/pages/writing-nft/index.vue
> ✨ Revamp landing

- src/components/NFTPage/ChainDataSection/index.vue
- src/components/NFTPage/EventList/Table.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
> ✨ Show message in class page event table

- src/components/EventModal/Collect/index.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/nuxt.config.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/util/api/index.js
Requires https://github.com/likecoin/likecoin-api-public/pull/424
Appears as 3d on desktop for collect dialog
Only appears in mobile for NFT detail page
> ✨ Show NFT model in NFT detail page and collect dialog

- src/components/NFTPortfolio/TopUsersList.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/_id/index.vue
- src/pages/dashboard/index.vue
- src/util/api/index.js
> ✨ Add top fan-ed creator list in dashboard

- src/pages/dashboard/index.vue
- src/util/api/index.js
- src/util/misc.js
> 🚸 Limit top ranked creators and top user list length

- src/mixins/nft.js
> 🚸 Show purchaser in nft message list

- src/components/NFTMessage/Identity.vue
- src/components/NFTMessage/index.vue
- src/pages/nft/class/_classId/_nftId.vue
> 🩹 Fix NFT details UI for phone

- src/components/UserStats/Controller.vue
Added `createdTotalSales` in computed. @AuroraHuang22 can work on UI
> ✨ Add `createdTotalSales` in user stats

- src/components/NFTCampaign/Item.vue
- src/components/NFTCampaign/ItemBase.vue
- src/mixins/nft.js
Redirect uncollectable NFT to the class details page
Before
After
> 🐛 Disable uncollectable in latest WNFT

- src/components/NFTCampaign/ItemBase.vue
- src/components/NFTSupply/Row.vue
- src/components/NFTSupply/Table.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> 💄 Adjust disabled NFT feed UI

- functions/pubsub/handlers.js
- functions/pubsub/index.js
> 🚧 Add event handler for transfer and purchase

- src/server/api/routes/users/v2/email.js
- src/server/api/routes/users/v2/follow.js
> ✨ Handle legacy followees

- src/components/MenuItem.vue
- src/components/NFTPortfolio/MainView.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/portfolio.js
- src/pages/_id/index.vue
- src/pages/dashboard/index.vue
> ✨ Add creator filter in portfolio

- src/components/MenuItem.vue
- src/components/MenuList.vue
- src/components/NFTPortfolio/MainView.vue
- src/mixins/portfolio.js
> 🚸 Sort and make filter list scrollable

- src/components/EventModal/Collect/index.vue
- src/nuxt.config.js
https://developer.chrome.com/blog/modulepreload/
> ⚡️ Improve model-viewer prefetch

- src/components/EventModal/Collect/index.vue
- src/pages/nft/class/_classId/_nftId.vue
> 🔧 Fine tune default camera angle for new model

- src/pages/notifications/index.vue
- src/store/modules/wallet.js
- src/util/api/index.js
Ref: https://github.com/likecoin/likecoin-chain-tx-indexer/pull/86
> ⚡️ Simplify API call for notification events

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/notifications/index.vue
- src/store/modules/wallet.js
> ✨ [Notifications/] Add notification of mint events with followees

- src/server/api/routes/users/v2/follow.js
Fix issue https://github.com/likecoin/liker-land/issues/980
> 🐛 Fix `isValidFollowee()` function call error

- src/mixins/portfolio.js
Mysteriously commented in https://github.com/likecoin/liker-land/pull/947/files#diff-2e6c34fe0fb814e6c3d9a72705a4aecdb98ac63074ea0491a2869fdaf00d5fc8R363
> 🐛 Fix display state never fetched

- src/components/UserStats/Controller.vue
- src/components/UserStats/Item.vue
- src/components/UserStats/MyDashboard.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/dashboard/index.vue
> 💄 [Dashboard/] Add total sales to dashboard

- src/components/EventModal/Collect/index.vue
> 💄 Adjust model viewer size

- src/components/EventModal/Collect/index.vue
- src/mixins/nft.js
- src/mixins/wallet.js
- src/store/modules/wallet.js
> 🎨 Better fetch session user data

- src/components/SiteHeader.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/notifications/index.vue
> 💄 Update notification label

- src/components/EventModal/Collect/index.vue
- src/mixins/nft.js
Depends on https://github.com/likecoin/likecoin-api-public/pull/432
> ✨ Buy listing NFT with credit card

- src/pages/writing-nft/index.vue
- src/store/modules/wallet.js
- src/util/api/index.js
Note that the complexity of getting API will go from 1 to N, where N is the number of followees.
> 🎨 Mock NFT mint event for ISCN transfer by replacing chain API

- src/components/NFTImageGraphic.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/class/_classId/index.vue
desktop
tablet
mobile
no creator's message
> 💄 [ClassDetails/] Add CTA section

- functions/package-lock.json
- functions/package.json
- src/package-lock.json
- src/package.json
https://github.com/likecoin/likecoin-wallet-connector/releases/tag/v0.18.0
> ⬆️ Upgrade @likecoin-wallet-connector to v0.18.0

- src/components/ButtonV2.vue
Normal
Active
Normal
Hover
Active
Hover
> 🩹 Fix button behavior

- src/layouts/default.vue
- src/nuxt.config.js
https://i18n.nuxtjs.org/seo
Adds list of locale in meta/link
> 🔍️ Add i18n head

- src/server/api/middleware/auth.js
Seems we took out the wallet param
> 🐛 FIx email verification check middleware

- src/components/NFTPortfolio/MainView.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/portfolio.js
- src/store/modules/nft.js
- src/util/nft.js
> 🎨 Set type as default sorting

- src/util/api/index.js
> 👔 Rank top fans by actual paid LIKE

- src/locales/zh-Hant.json
- src/pages/nft/class/_classId/index.vue
> 💬 Update wording for nft-book content

- src/components/AlertBanner.vue
- src/components/ButtonV2.vue
- src/layouts/default.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> ✨ Add alert banner for NFT Book sale

- functions/package-lock.json
- functions/package.json
- src/constant/network.js
- src/package-lock.json
- src/package.json
> ✨ Support Leap Wallet

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/settings/email/index.vue
- src/server/api/routes/users/v2/email.js
Further UI improvement is welcome.
Not sure whether we should also provide some warning sentence, in case of abuse of this mode.
> 🚧 Accept predefined email from URL

- src/components/EventModal/Collect/index.vue
> 👔 Hide Stripe payment

- src/components/NFTPage/CollectCTA.vue
- src/pages/nft/class/_classId/index.vue
Update the wrapping with the collect CTA in the column UI.
> 💄 Update collect CTA with column UI

- .github/workflows/deploy-main.yml
- .github/workflows/deploy-rinkeby.yml
firebase-tools>=12 deprecate node@14
> 💚 Pin firebase-tools version in CD

- src/components/NFTMessage/Identity.vue
- src/components/NFTPage/Recommendation.vue
- src/mixins/nft.js
- src/mixins/wallet.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
> ✨ Add purchase recommendation

- src/pages/_id/index.vue
- src/pages/civic/index.vue
- src/pages/getapp.vue
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/writing-nft/about.vue
- src/pages/writing-nft/index.vue
https://v8.i18n.nuxtjs.org/guide/seo/#feature-details
> 🔍️ Remove canonical link in head since i18n generates one

- src/components/NFTCampaign/ItemBase.vue
Should remove after proper fix with initial batch value
> 💩 Hide broken supply table if price mismatch

- src/components/NFTCampaign/ItemBase.vue
- src/components/NFTSupply/Row.vue
> 💩 Disable broken supply table if price mismatch

- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
try to troubleshoot this error log
> 💩 Remove JSON.stringify in error log to debug 500 error

- src/components/NFTSupply/Row.vue
The issue is probably within `<NFTCampaignItem>`, should investigate further
> 💩 Fix SSR error

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/claim/index.vue
- src/pages/settings/email/verify/_token.vue
- src/server/api/routes/users/v2/email.js
- src/store/modules/wallet.js
- src/util/api/index.js
> ✨ Display pending claim W.NFT count after email verification

- src/components/EventModal/Collect/index.vue
- src/util/ui.js
> 💫 Add tx pending animation

- src/components/NFTCampaign/Item.vue
- src/components/NFTCampaign/ItemBase.vue
- src/components/NFTPage/SupplySection.vue
- src/components/NFTSupply/Table.stories.js
- src/components/NFTSupply/Table.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/util/writing-nft.js
> ✨ Support base price for `<NFTSupplyTable/>`

- src/util/api/index.js
Depends on https://github.com/likecoin/likecoin-chain-tx-indexer/pull/110
> 👔 Exclude iscn owner for collected W.NFT

- src/components/TxModal.vue
- src/layouts/default.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/store/modules/getters/ui.js
> 🥅 Add notice and tx blocking when chain upgrading

- src/components/SiteHeader.vue
For some reason using `append` slot for ButtonV2 here does not work at all
> 💄 Move notification icon onto site header

- src/pages/nft/class/_classId/_nftId.vue
https://likecoin-fdn.slack.com/archives/C03EP8VB7BP/p1685708813755589
> 🔥 [_nftId/] Remove PrimitiveDisclaimer

- src/components/UserStats/Item.vue
- src/components/UserStats/MyDashboard.vue
- src/pages/dashboard/index.vue
> 💄 [Dashboard] Improve stats layout

- src/components/UserStats/IncomeDetailsDialog.vue
- src/components/UserStats/IncomeTable.vue
- src/components/UserStats/MyDashboard.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> 🐛 [Dashboard] Fix income list items without NFT name 

- src/components/AuthRequiredView.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/claim/index.vue
- src/util/api/index.js
> ✨ Support claiming NFT Book

- functions/package-lock.json
- functions/package.json
- src/components/EventModal/Collect/index.vue
- src/constant/network.js
- src/package-lock.json
- src/package.json
Base on https://github.com/likecoin/liker-land/pull/1132
> 🔧 Enable keplr-mobile

- src/components/NFTPage/CollectorList/index.vue
collect own nft
collect 0 nft
reserve nft
> 🚸  Display the count of nfts reserved or collected by creator

- src/mixins/nft.js
Related: https://github.com/likecoin/likecoin-api-public/pull/484
> 🚸 Prefill email for Stripe if available

- src/store/modules/nft.js
> ⚡️ Use LCD API for ISCN query

- src/components/NFTEditionSelect.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
single item with name & description
single item without name & description
out of stock
> 💄 Add NFT name & description for single edition

- src/components/NFTBook/ItemCard.vue
> ⚡️ Reduce size of NFT book cards

- src/components/NFTBook/ItemCard.vue
- src/components/NFTPage/ControlBar.vue
- src/constant/index.js
- src/mixins/nft.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
> 👔 Change pricing method of NFTBook from LIKE to USD

- src/store/modules/nft.js
TODO: should remove `metadata.iscn_record ` and reuse ISCN data store
> ⚡️ Reduce duplicated iscn fetch

- src/server/api/routes/nft/metadata.js
client expect iscnData to have `owner` in some logic
> 🐛 Fix API return format

- src/components/Icon/SkipNext.vue
- src/components/NFTBook/Hero.vue
- src/locales/en.json
> 💄 Use icon button for hero animation control

- src/constant/index.js
- src/pages/index.vue
> [TAS-125] 🔧 Add back ChatGPT NFT Book

- src/components/NFTBook/Hero.vue
> [TAS-127] 🐛 Fix hero blocking menu

- src/store/modules/nft.js
- src/util/nft.js
Fix display error derived from https://github.com/likecoin/liker-land/pull/1220#issuecomment-1635910968
Depends on https://github.com/likecoin/likecoin-chain-tx-indexer/pull/119
https://github.com/likecoin/liker-land/assets/33746295/8b427f56-7b0a-4040-9a42-9a66826e65ab
> 🐛 [Portfolio] Fix transferred NFT timestamp missing error

- src/components/NFTPage/ControlBar.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
> [TAS-123] 🚑 Conditionally show control bar for NFT Book

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/notifications/index.vue
https://github.com/likecoin/liker-land/assets/17264716/9f2c29ee-12d1-48bd-af72-22be0f303305
> [TAS-45] ⚡️ Paginate notification list

- src/components/NFTBook/ItemCard.vue
- src/components/NFTCover.vue
- src/components/NFTEditionSelect.vue
> [TAS-143] 📱 Reorder collect button for `<NFTBookItemCard/>`

- src/components/NFTMessage/Text.vue
- src/components/NFTMessage/index.vue
- src/pages/notifications/index.vue
> [TAS-173] 🩹 Properly handle line break in message

- src/store/modules/nft.js
https://github.com/likecoin/liker-land/assets/33746295/029a750a-bcf5-4ba1-b27b-5758daaa68eb
> 🐛 Fix class filter doesn't includes all creators bug

- src/pages/nft/class/_classId/index.vue
Related to https://github.com/likecoin/likecoin-api-public/pull/505
> [TAS-107] 👽 Use `index` field for `priceIndex`

- src/components/NFTPortfolio/MainView.vue
- src/util/nft.js
Depends on https://github.com/likecoin/likecoin-chain-tx-indexer/pull/122
> 🐛 Navigate to NFT details page on portfolio item click

- src/server/api/routes/nft/metadata.js
Refactor internal functions before making API allows clients to select class data categories.
Writing NFT
NFT book
> [TAS-48] ✨ `/metadata` API supports selectable return data fields

- src/components/AuthRequiredView.vue
- src/pages/nft/claim/index.vue
Now the action button is stick to the bottom
https://github.com/likecoin/liker-land/assets/17264716/3870be1b-5ef1-42fb-a0d4-7abcb5d04c69
> [TAS-218] 📱 Make claim button visible for mobile

- src/components/NFTBook/ItemCard.vue
- src/components/NFTPage/Recommendation.vue
- src/components/NFTViewOptionList.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
> [TAS-141] ⚡️ Lazy fetch recommendation data

- src/components/NFTPage/CollectCTA.vue
- src/pages/nft/class/_classId/index.vue
> 🐛 Fix undefined creator message

- functions/package-lock.json
- functions/package.json
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/wallet-login.js
- src/package-lock.json
- src/package.json
- src/store/modules/wallet.js
Based on https://github.com/likecoin/likecoin-wallet-connector/pull/34
> [TAS-308] 🌐 Update connect wallet copywriting

- src/components/Footer.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/nuxt.config.js
> [TAS-288] ✨ Add newsletter subscription in footer

- src/components/SocialFeedItem.vue
> [TAS-353] 💄 Adjust font size

- src/components/SocialFeedItem.vue
- src/pages/feed/index.vue
Removed extra elements and improve style when hovering hyperlinks
It is better to ignore whitespace when reviewing the code
> 🎨 Clean up index page feed UI

- src/components/AuthRequiredView.vue
- src/components/MobileStickyCard.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/claim/index.vue
> [TAS-347] ✨ Allow entering like1 address to claim nft

- src/pages/notifications/index.vue
> 💄 Shorten wallet display length

- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/pages/shopping-cart.vue
- src/store/modules/nft.js
> [TAS-374] ✨ Support check out shopping cart by card

- src/components/NFTPortfolio/Base.vue
- src/components/NFTViewOptionList.vue
> [TAS-282] 💄 Display collector/own stats for nftBook

- src/components/ButtonV2.stories.js
- src/components/ButtonV2.vue
- src/pages/index.vue
> [TAS-275] 💄 Update button theme in index page

- src/components/NFTPage/Recommendation.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- [🐛 Prevent self-following](https://github.com/likecoin/liker-land/commit/b1601e247db1d9169b940b4111d9fc2dc0aac66a)
- [💄 Fix missing pagination buttons](https://github.com/likecoin/liker-land/commit/f53e0e5aa4d3ced0d80e33ebaa19c6fb083048fb)
- [🚸 Add default recommend nfts for empty works](https://github.com/likecoin/liker-land/commit/dac45feaf6f0c82480eb0ec4fa2e4f48ccbb3600)
> [TAS-482] 🐛 Various fixes for recommendation list

- src/components/NFTBook/Shelf.vue
- src/pages/store/books.vue
- src/pages/store/index.vue
> [TAS-492] 💄 Apply shelf UI for /store/books

- src/layouts/default.vue
> 💩 Fix mysterious site menu z-index issue

- src/constant/network.js
- src/package-lock.json
- src/package.json
- src/store/modules/wallet.js
> ⬆️ Upgrade `@likecoin/wallet-connector` to v0.25.0

- src/constant/index.js
> [TAS-530] 👔 List 上行之詩

- src/package-lock.json
- src/package.json
Pick window.keplr automatically in keplr mobile dapp browser
> ⬆️ Upgrade `@likecoin/wallet-connector` to v0.25.1

- src/config/sitemap.js
Requires https://github.com/likecoin/likecoin-api-public/pull/540
> 🔍️ Add latest book classes to sitemap

- src/pages/_id/index.vue
- Use 301 for id page redirect
- redirect cosmos prefix to like prefix
> 🚸 Add 301 redirect for cosmos prefix

- src/components/NFTBook/ItemCard.vue
- src/mixins/nft.js
Prefer to use ISCN description in nft book pages
> [TAS-568] 👔 Use ISCN description for book pages

- src/config/sitemap.js
- src/nuxt.config.js
Hack mentioned in https://github.com/nuxt-community/sitemap-module/issues/122#issuecomment-633424117
> 🔍️ Set i18n in sitemap

- src/experiments/index.js
- src/experiments/recommend-connection-method.js
- src/mixins/wallet-login.js
- src/nuxt.config.js
> [TAS-304] 🧪 Apply AB test result for recommended wallet

- src/components/Identity/Identity.avatar.vue
- src/components/NFTPortfolio/UserInfo.vue
- src/components/UserInfoCard.vue
- src/components/UserStats/MyDashboard.vue
- src/mixins/wallet.js
- src/pages/_id/index.vue
- src/pages/feed/index.vue
> [TAS-541] 🚸 Allow copy wallet in feed page

- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/util/api/index.js
> [TAS-595] 💄 Display nft book buyer messages on collector list

- src/pages/nft/class/_classId/index.vue
ref: https://github.com/likecoin/likecoin-api-public/blob/master/test/api/oembed.test.ts#L133
> ✨ Add oembed discovery header for wnft

- src/mixins/nft.js
- src/pages/nft/claim/index.vue
- src/util/EventLogger.js
- src/util/api/index.js
https://github.com/likecoin/likecoin-api-public/pull/553
> 📈 Add gaClientId into stripe checkout calls

- src/components/EventModal/Collect/index.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> [TAS-770] ✨ Add share button in nft collect modal

- src/components/MenuIcon.vue
> 💄 Fix missing icon for article menu item

- src/components/NFTPage/ChainDataSection/Metadata.vue
- src/components/NFTPage/ChainDataSection/index.vue
- src/components/NFTPage/PreviewCard.vue
- src/mixins/nft.js
- src/pages/nft/claim/index.vue
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/reader.vue
- src/store/modules/nft.js
https://github.com/likecoin/likecoin-api-public/pull/556
> [TAS-787] ✨ Support hideDownload flag in nft book

- src/util/EventLogger.js
adblock might just eat the function without callback
> 🚑️ Add timeout fallback for getGaClientId

- src/components/NFTBook/Hero.vue
Prevent double animation page when onboard from index to bookstore
> 💩 Disable book store animation

- src/mixins/nft.js
Related: https://github.com/likecoin/likecoin-api-public/pull/568
> 💄 Round to 1 d.p. for HKD price

- src/pages/nft/claim/index.vue
Requires https://github.com/likecoin/likecoin-api-public/pull/543
> [TAS-646] 💄 Allow directly claim free book via wallet

- src/components/MenuIcon.vue
- src/components/SiteHeader.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> 💄 Replace notification with portfolio in side menu

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/index.vue
> [TAS-816] 👔 Update index page content before the new index is finished

- src/components/NFTPage/CollectorList/index.vue
> [TAS-743]💄 Add title to collector table

- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
https://github.com/likecoin/liker-land/assets/17264716/551ad914-e9b0-446c-b313-8ada980ee522
https://github.com/likecoin/liker-land/assets/17264716/d867bcee-c332-4bb7-b2ab-fe8a669e5be3
> 🚑️ Fix control bar for NFT Book

- src/components/NFTBook/EditionCompareTableColumn.vue
> [TAS-789]💄 Adjust the spacing of book edition card

- functions/package.json
- src/components/Gutenberg/DownloadItem.vue
- src/nuxt.config.js
- src/pages/gutenberg/free-audio-books.vue
- src/pages/gutenberg/index.vue
- src/plugins/plyr.js
- Remove the plyr package, and use iframe and CSS for RWD.
- Improve the readability of the classes.
- Extract reusable components.
> ♻️ PG page improvements

- src/components/NFTPage/CollectorList/Item.vue
- src/components/NFTPage/CollectorList/index.vue
> 📲 Improve mobile version UI for collectorList

- src/components/NFTBook/ItemCard.vue
> [TAS-871] 🎨 Add ellipsis for iscnWorkAuthor

- src/components/NFTEditionSelect.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/pages/nft/claim/index.vue
https://github.com/likecoin/likecoin-api-public/pull/586
> [TAS-920] ✨ Add isPhysicalOnly support for book edition and claim

- src/components/Gutenberg/DownloadItem.vue
- src/pages/gutenberg/free-audio-books.vue
- src/pages/gutenberg/index.vue
> [TAS-976] 🔍 Replace all redirects in PG with anchor links

- src/components/NFTPage/Recommendation.vue
- src/constant/index.js
- src/mixins/nft.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/util/nft.js
The priority of recommended content:
Book - different author **>** WNFT - different author **>** Book - different authors **>** WNFT - different authors
> [TAS-799] 👔 Update content of recommendations for book NFT

- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/util/api/index.js
https://github.com/likecoin/likecoin-api-public/pull/595
> [TAS-931] 📈 Send utm params to checkout API

- src/pages/store/index.vue
`classId` happens to be `string|string[]`
> 🐛 Fix class id list was directly used in prefetch header and json ld

- src/components/Footer.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> [TAS-1019] 🔍️ Add about nft book page in footer

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/claim/index.vue
> [TAS-1064] 🥅 Guard invalid claim wallet address

- src/mixins/nft-collection.js
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
Requires https://github.com/likecoin/likecoin-api-public/pull/605
> 🚸 Pass user email to Stripe checkout if available

- src/components/EventModal/Collect/MethodButton.vue
- src/components/EventModal/Collect/index.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
- src/store/modules/nft.js
> [TAS-489] ✨ Add UI for discounted LIKE price

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/claim/index.vue
Depends on https://github.com/likecoin/likecoin-api-public/pull/596
> [TAS-881] 💄 Update text for claiming auto delivery NFT book

- src/components/EventModal/Collect/index.vue
> 🎨 Flip discount percentage

- src/components/AuthRequiredView.vue
- src/mixins/wallet.js
Make url changes before wallet connect pop up, so that we can save the url in localstorage
> 🚸 Change route on unauth nav to feed

- src/components/NFTBook/EditionCompareTableColumn.vue
- src/components/NFTPage/ControlBar.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/nft.js
**only 1 edition is available**
**out of stock**
> [TAS-1026] 🐛 Fix button behavior for unavailable editions

- functions/package-lock.json
- functions/package.json
- src/constant/network.js
- src/mixins/wallet-login.js
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
- src/pages/auth/redirect.vue
- src/store/modules/wallet.js
https://github.com/likecoin/likecoin-wallet-connector/pull/53
> [TAS-1004] ✨ Support wallet connector authcore redirect login

- src/mixins/crisp.js
- src/pages/index.vue
> [TAS-1137] 👔 Show crisp in index as non-zh publish CTA

- src/components/NFTPage/Recommendation.vue
- src/components/NFTPortfolio/Item.vue
- src/components/NFTPortfolio/MainView.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> [TAS-970] 💄 Add recommendation section to pages

- src/pages/nft/claim/index.vue
> [TAS-1067] 💄 Add recommendation section to claim page

- src/nuxt.config.js
> 🔒️ Allow blob in style csp for epub

- src/components/NFTEditionSelect.vue
- src/components/NFTEditionSelectItem.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
> [TAS-1103]💄 Display coupon discount for edition

- src/mixins/nft.js
> [TAS-1256] 🐛 Fix buyer message not shown in nft page

- src/mixins/nft.js
- src/pages/nft/claim/index.vue
`nft` mixin shadowed `nft-or-collection` mixin, should change order
> 🐛 Fix mixin conflict

- functions/package-lock.json
- functions/package.json
- src/nuxt.config.js
- src/package-lock.json
- src/package.json
Since we are not actively using any feature of pwa, and this cause extra headache on debug and client storage, we should remove it for now
> 🔥 Remove @nuxtjs/pwa

- src/pages/auth/redirect.vue
sessionStorage is used in setItem
> 🐛 Fix sessionStorage and localStorage misalign

- src/pages/nft/class/_classId/index.vue
Should redirect to stripe checkout if any price is set >0
> [TAS-1439] 🐛 Fix custom price logic for free editions

- src/plugins/ui-plugin.client.js
Improve loading ux when user reach a new page of nft book
> 🚸 Remove lazy load throttle

- src/pages/nft/class/_classId/index.vue
- src/server/api/routes/nft/metadata.js
https://github.com/likecoin/likecoin-api-public/pull/645
> 🥅 Treat 404 from book store API

- src/pages/nft/collection/_collectionId/index.vue
Works in combine with https://github.com/likecoin/likecoin-api-public/pull/648
> ✨ Support free purchase in colleciton

- src/components/NFTBook/TippingDialog.vue
- src/mixins/nft-collection.js
- src/pages/nft/collection/_collectionId/index.vue
- src/store/modules/nft.js
> 🐛 Fix defaultPriceInfo undefined

- src/mixins/nft-collection.js
- src/store/modules/nft.js
> 👽 Retrieve discount information from the flatDiscount field on the collection page

- src/components/NFTBook/Cover.vue
- src/components/NFTBook/CoverWithFrame.vue
Demo code
```jsx
<div class="m-[4rem] space-y-[4rem] w-full max-w-[320px] mx-auto">
<NFTBookCover
src="https://static.like.co/thumbnail/?url=https%3A%2F%2Farweave.net%2F8emneYqcnClqzsEBcRIaQ7tA4pKlcbqTQ1u8OK8VVIU&width=300"
/>
<NFTBookCoverWithFrame
src="https://static.like.co/thumbnail/?url=https%3A%2F%2Farweave.net%2F8emneYqcnClqzsEBcRIaQ7tA4pKlcbqTQ1u8OK8VVIU&width=300"
/>
</div>
```
> 💄 Add new NFT Book Cover components

- src/components/NFTPage/ChainDataSection/Metadata.vue
- src/components/NFTPage/ChainDataSection/index.vue
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
> 🚸 Hide content fingerprint links for book

- src/layouts/default.vue
- src/pages/reader/epub.vue
https://developer.mozilla.org/en-US/docs/Web/API/Cache
Experimental, but this API is widely supported and has large size quota compared to localStorage
TODO: purge unused key according to certain logic on mount
> [TAS-1148] ⚡️ Use cache API to cache epub file

- src/pages/nft/claim/index.vue
Avoid the situation where you are already logged in but not redirected.
> 🐛 Fix automatic redirection after login

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/settings/index.vue
> ✨ Add clear reader cache button

- src/components/NFTClaim/MainSection.vue
- src/components/NFTClaim/OptionList.vue
- src/pages/nft/claim/index.vue
> [TAS-1632] 💄 Update download dropdown button

- src/pages/reader/pdf.vue
Strange error when opening pdf for first time, haven't have time to investigate yet
> 🥅 Catch contentWindow is undefined

- src/pages/reader/epub.vue
Reverted https://github.com/likecoin/liker-land/pull/1626 to simplify the hack @nwingt
> [TAS-1711] 💩 Check for epub book and rendition exist before creating

- src/nuxt.config.js
- src/pages/index.vue
> [TAS-1744] ✨ Add Instagram feed

- src/pages/index.vue
Remove the hack after paying for the widget service
> 👽 Remove margin hack for Instagram feed

- src/pages/nft/claim/index.vue
Force-fetch collected classes when redirect back to the bookshelf.
task: [[bug] Books on the bookshelf have not been updated correctly](https://www.notion.so/likecoin/bug-Books-on-the-bookshelf-have-not-been-updated-correctly-6e7a79d25ccd473381674f4dd9b7c6ac?pvs=4)
> [TAS-1743] 🎨 Force refetch classes after claiming

- src/components/NFTMessage/Identity.vue
- src/components/NFTPortfolio/MainView.vue
> 💄 Add ellipsis to Identity

- src/mixins/reader.js
To always use `fetch` to avoid `cache.add` error causing another xhr from axios
> [TAS-1784] ♻️ Rewrite reader fetch to avoid duplicate on cache err

- src/components/NFTBook/CoverWithFrame.vue
- src/components/NFTBook/EditionCompareTableColumn.vue
- src/components/NFTBook/ItemCard.vue
- src/components/NFTPage/PreviewCard.vue
- src/components/NFTPortfolio/Base.vue
> [TAS-1785] 💄 Replace old cover with new one

- src/pages/reader/epub.vue
TODO: figure out why epub reader is mounted twice in some instance
> [TAS-1790] 🎨 Clean up epub on unmount

- src/pages/gutenberg/free-audio-books.vue
There is a delay in the page when the last keyword is deleted, so I use debounced here.
[https://rinkeby.liker.land/zh-Hant/gutenberg/free-audio-books](https://rinkeby.liker.land/zh-Hant/gutenberg/free-audio-books)
> [TAS-1770] 🔍 Display all result if no searchKeyword

- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/reader.js
- src/pages/reader.vue
- src/pages/reader/epub.vue
- src/pages/reader/pdf.vue
> [TAS-1767] 🚸 Add ebook download progress

- src/pages/reader/pdf.vue
https://github.com/likecoin/pdf.js/pull/6
> [TAS-1757] ⚡️ Transfer arraybuffer directly in pdf reader postMessage

- src/components/TxModal.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/wallet.js
- src/pages/settings/index.vue
- src/util/links.js
> [TAS-1543] ✨ Add export seed word link in setting

- src/components/NFTClaim/OptionList.vue
- src/pages/nft/claim/index.vue
- Move asyncData to mounted since we don't really need those info for SSR
- Check payment status on mount
- Also send claim token on GET payment status to prepare for API changes
> ♻️ Simplify claim page mounted logic

- src/components/Footer.vue
- src/components/Substack.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/gutenberg/index.vue
- src/util/api/index.js
> [TAS-1811] 💄 Implement custom UI for Substack

- src/components/UserInfoCard.vue
> [TAS-1899] 💄Add ellipsis to displayName in UserInfoCard

- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/wallet-login.js
- src/package-lock.json
- src/package.json
- src/pages/nft/claim/index.vue
- src/store/modules/wallet.js
https://github.com/user-attachments/assets/6d87d737-691f-46ad-9d12-528ec872e811
> 🚸 Open authcore register screen on sign up click

- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
Related to https://github.com/likecoin/nft-book-press/issues/156#issuecomment-2266338821
> 🐛 Fix index field is not used in book price

- src/mixins/nft.js
> 🚸 Change control bar price according to index

- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
https://developers.google.com/search/docs/appearance/structured-data/merchant-listing#3d-model-example
> 🔍️ Move 3dModel to subjectOf

- src/components/NFTBook/ItemCard.vue
- src/components/NFTBook/Shelf.vue
- src/components/NFTCollection/ItemCard.vue
- src/pages/nft/collection/_collectionId/index.vue
> [TAS-2015] Fix broken collection item grid

- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/pages/shopping-cart/book.vue
- src/util/api/index.js
https://github.com/likecoin/likecoin-api-public/pull/731
> [TAS-2045] 📈 Send referrer on purchase

- src/components/Dialog.vue
- src/components/NFTBook/CrossSellDialog.vue
- src/components/NFTBook/TippingDialog.vue
- src/constant/index.js
- src/locales/en.json
- src/locales/zh-Hant.json
- src/mixins/cross-sell.js
- src/mixins/nft-or-collection.js
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
> [TAS-2039] ✨ Add cross sell dialog

- src/components/NFTPortfolio/MainView.vue
> 💄 Fix bookshelf loading placeholder for desktop

- src/pages/nft/claim/index.vue
Felt like I had been fixing similar issue over and over again..
> [TAS-1550] 🐛 Fix invalid img src and description in claim

- src/components/NFTPortfolio/FilterDropdown.vue
> [TAS-2126] 💄 Fix filter dropdown overflow

- src/components/Footer.vue
> 🐛 Fix click event in footer items

- src/components/NFTBook/EditionCompareTableColumn.vue
- src/components/NFTCollection/ItemCard.vue
- src/components/NFTPortfolio/Card.vue
Please review with white-space off
Before
After
> 💄 Fix edition/collection card overflow

- src/components/ShoppingCart/ListRow.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> 💬 Update translation for purchase channel

- src/components/NFTFeatured/index.vue
- src/components/NFTPortfolio/SubscriptionForm.vue
- src/components/SiteHeader.vue
- src/mixins/wallet-login.js
- src/mixins/wallet.js
- src/pages/notifications/index.vue
- Prompt error on login fail (except user reject)
- Show error on site header connect fail
> 🚸 Prompt login error

- src/mixins/nft.js
> 👔 Remove duplicate recommendations

- src/mixins/cross-sell.js
- src/pages/nft/claim/index.vue
Response to https://github.com/likecoin/liker-land/pull/1766#pullrequestreview-2281035536
> 🎨 Turn state to computed prop

- src/components/ShoppingCart/ListRow.vue
- src/mixins/nft.js
> 🐛 Fix invalid productPrice

- src/pages/nft/claim/index.vue
> [TAS-2182] 🚸 Display logged in email in claim page

- src/nuxt.config.js
Ref https://sentry.nuxtjs.org/guide/profiling
> [TAS-2195] 🔧 Fix sentry tracing config

- src/pages/reader/epub.vue
fixes [LIKER-LAND-4GM](https://likerland-team.sentry.io/issues/5511414989/)
> 🥅 Catch undefined epub location.start

- src/components/NFTPortfolio/Empty.vue
- src/locales/en.json
- src/locales/zh-Hant.json
> [TAS-2196] 🚸 Add Crisp help for empty content in /bookshelf

- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
Fixes [LIKER-LAND-4NA](https://likerland-team.sentry.io/issues/5774229249/)
> 🐛 Fix missing nftId for non-wnft control bar collect

- src/static/vendor/fbq.js
Reverts likecoin/liker-land#1749
> ⏪️ Revert "📈 Add Facebook Pixel"

- src/components/SiteHeader.vue
- src/mixins/wallet.js
- src/pages/nft/claim/index.vue
- Should use login address instead of connected wallet address
> [TAS-2134] 🐛 Fix free purchase without email

- src/pages/nft/claim/index.vue
Related: https://github.com/likecoin/likecoin-api-public/pull/753
> 📈 Add utm in free purchase

- src/components/NFTBook/CrossSellDialog.vue
- src/mixins/nft.js
- src/mixins/utm.js
- src/pages/nft/claim/index.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/pages/shopping-cart/book.vue
Related: https://github.com/likecoin/likecoin-api-public/pull/758
> 📈 Pass gclid if exists on checkout and redirect

- src/pages/nft/claim/index.vue
Require: https://github.com/likecoin/likecoin-api-public/pull/756
> 🚸 Set auto deliver for single item cart deliver

- src/pages/nft/claim/index.vue
Require: https://github.com/likecoin/likecoin-api-public/pull/755
> 🔊 Post loginMethod on claim

- src/components/NFTBook/CrossSellDialog.vue
- src/mixins/nft.js
- src/mixins/utm.js
- src/pages/nft/claim/index.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/pages/shopping-cart/book.vue
Related: https://github.com/likecoin/likecoin-api-public/pull/760
> 📈 Add gad_source support

- src/components/NFTMessage/Identity.vue
- src/components/NFTPage/Recommendation.vue
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
> 👔 Improve recommendation display items & label

- src/pages/nft/claim/index.vue
Related: https://github.com/likecoin/likecoin-api-public/pull/762
> ✨ Post loginMethod for free book

- src/pages/index.vue
- src/tailwind.config.js
> 💄 Show up to 10 books in landing page

- src/mixins/crisp.js
- src/server/api/routes/users.js
- src/server/api/routes/users/v2/auth.js
- src/server/api/util/crisp.js
- src/store/modules/wallet.js
- src/util/EventLogger.js
https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/identity-verification/
> 🔒️ Set crisp token on v2 login, fix showCrisp event mess up

- src/pages/reader/epub.vue
> [TAS-2258] 🐛 Fix epub reader font size inconsistent

- src/components/NFTBook/GiftDialog.vue
- src/pages/nft/claim/index.vue
- src/pages/nft/gift/index.vue
- src/pages/shopping-cart/book.vue
Require: https://github.com/likecoin/likecoin-api-public/pull/747
> [TAS-2201] ✨ Support gift in book cart

- src/pages/reader/epub.vue
> [TAS-2304] ✨Show nested toc for epub reader

- src/static/vendor/fbq.js
Reverts likecoin/liker-land#1831
> ⏪️ Revert "📈 Add 2nd fb pixel"

- src/mixins/nft.js
- src/nuxt.config.js
old logic was for wnft which requires wallet exists before checkout, now we sell book for guest checkout
> 👔 Always load stripe js

- src/components/NFTBook/CrossSellDialog.vue
- src/mixins/nft.js
- src/mixins/utm.js
- src/pages/nft/claim/index.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/pages/shopping-cart/book.vue
- src/util/EventLogger.js
Related: https://github.com/likecoin/likecoin-api-public/pull/782
https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc#fbp
> [TAS-2317] 📈 Add fbClickId and eventID in fbq

- src/nuxt.config.js
- src/pages/nft/class/_classId/index.vue
Reverts likecoin/liker-land#1855
[LIKER-LAND-4RP](https://likerland-team.sentry.io/issues/5944612397/)
> ⏪️ Revert "[TAS-2291] 📈 Target specific audience for replay"

- src/mixins/utm.js
https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc
> 📈 Fetch fbc from cookie and format qs

- src/components/NFTPortfolio/Item.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/share/index.vue
- src/store/modules/nft.js
- src/util/api/index.js
`this.lazyFetchNFTClassAggregatedData()` resets the legacy owner information, setting `ownerCount` to 0.
When `ownerCount` is 0, the `open book` button will not be displayed.
> [TAS-2244] 🐛Update latest ownerInfo for Item card

- src/components/ShoppingCart/ListRow.vue
> 🐛 Handle floating point precision issue in tippingAmount

- src/components/NFTBook/ItemCard.vue
- src/components/NFTBook/SpecTableItemAccessMethod.vue
- src/components/NFTBook/SpecTableItemAvailableFormat.vue
- src/components/NFTBook/SpecTableValue.vue
> [TAS-2374]💄 Update specTableItem label style for campaign item

- src/components/NFTBook/TippingDialog.vue
> [TAS-2431] 🚸 Update tipping label formatting

- src/components/NFTBook/CrossSellDialog.vue
- src/mixins/nft.js
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/pages/shopping-cart/book.vue
Need https://github.com/likecoin/liker-land/pull/1823
> [TAS-2420] ✨ Use auth token for book checkout

- src/components/NFTBook/CollectionItemCard.vue
- src/components/NFTPage/Recommendation.vue
- src/components/NFTPortfolio/MainView.vue
- src/mixins/nft-collection.js
- src/mixins/nft.js
- src/pages/nft/class/_classId/_nftId.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
> [TAS-1063] ♻️ Move recommendation logic to component

- src/pages/reader.vue
mitigate issue where nftid fetch causes refresh to error out
> 🚸 Store nftId in url for reader page

- src/components/NFTPage/Recommendation.vue
- src/constant/index.js
- src/mixins/cross-sell.js
https://github.com/user-attachments/assets/8e81f5f1-632a-4e73-b237-5d351c1417a7
> [TAS-2482] ✨ Prioritize cross-sell items in the recommendation list

- src/nuxt.config.js
https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox?hl=zh-tw
> [TAS-2474] 🔍️ Add SearchAction in JSON-LD

- src/constant/index.js
https://github.com/user-attachments/assets/fa4fb2e1-fd1c-4082-99e4-5ea2cfb8e0f2
> [TAS-2511] 🔧 Add cross sell items

- src/components/NFTBook/ItemCard.vue
- src/components/NFTBook/SpecTableItemDateReleased.vue
- src/components/NFTCollection/ItemCard.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
> 💄 Add release/publish date in book page and JSON-LD

- src/pages/store/index.vue
- src/server/api/util/airtable.js
> [TAS-2515] ✨ Support tag description

- src/components/NFTPage/Recommendation.vue
- src/constant/index.js
- src/mixins/cross-sell.js
https://likecoin-fdn.slack.com/archives/C03EP8VB7BP/p1730283356028679
> 🔧 Recommend books by the same author for FengHuoShanLin

- src/constant/index.js
https://likecoin-fdn.slack.com/archives/C03EP8VB7BP/p1730798495749949
> 👔 Reorder recommendation list for Amazing Grace Worship

- src/constant/index.js
https://likecoin-fdn.slack.com/archives/C03EP8VB7BP/p1730951866033869
> 🔧 Update cross-sell items for Dung

- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/store/index.vue
- src/server/api/util/airtable.js
- src/store/modules/nft.js
This PR also added backs the Chinese language filter
> [TAS-2522] 👔 Update listing page logic

- src/pages/store/index.vue
- src/util/EventLogger.js
https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events#view_item_list
> 📈 Add list related event

- src/pages/store/index.vue
- src/util/EventLogger.js
https://cloud.google.com/retail/docs/user-events#formats
> [TAS-2590] 📈 Add more GRE events

- src/components/NFTEditionSelectItemV2.vue
> 🐛 Fix selectItem height

- src/components/ButtonV2.vue
- src/components/LandingPage/FeatureItem.vue
- src/locales/en.json
- src/locales/zh-Hant.json
- src/pages/index.vue
> [TAS-2688] ✨ Add search bar to home page

- src/components/NFTBook/ItemCard.vue
> 🚸 Add hover state for publisher

- src/pages/store/index.vue
> 🐛 Fix tag list overflow issues

- src/mixins/nft-or-collection.js
> [TAS-3055] 🎨 Use ISCN name as NFTBook listing name

- src/components/NFTEditionSelect.vue
- src/pages/nft/class/_classId/index.vue
- src/pages/nft/collection/_collectionId/index.vue
- src/store/modules/cart.js
Requires https://github.com/likecoin/likecoin-api-public/pull/845
> [TAS-3037] 👔 Enable add to cart to free items

- src/mixins/utm.js
https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc?locale=zh_HK
> 🐛 Fix invalid fbc

- src/components/NFTBook/ItemCardV2.vue
> 🚨 Fix route missing id

- src/server/api/routes/bookstore/index.js
- src/util/api/index.js
> 🚑 Correct condition for TAG_NOT_FOUND

- src/pages/reader/pdf.vue
> [TAS-3208] 💄 Add home/back button in PDF reader

- src/nuxt.config.js
- src/pages/index.vue
- src/pages/store/articles.vue
- src/pages/store/index.vue
we want the base schema in nuxt config to also show up on index and store
changing hid would allow that
> 🔍️ Fix jsonld was overwritten in index

- src/constant/index.js
production already set, update for testnet only
> [TAS-3182] 👔 Update cross sell for bottleshiu

- src/pages/reader.vue
Cannot read book when logged in if no login is required to read book
> [TAS-3235] 🐛 Fix unable to read not login required book when logged in

- src/components/NFTBook/CrossSellDialog.vue
- src/constant/index.js
- src/pages/nft/class/_classId/index.vue
> [TAS-3267] 💬 Update cross-sell dialog title for Bottle Shiu
