src/assets/css/_global.scss

make font flash less obvious, make missing simplified chinese font less obvious

🚸 Add fallback local fonts in font-family

---

src/components/ContentList.vue

guess: the transition `in-out` cause the old list shadowed the new list, thus not lazy load (default event mode) won't trigger
seems not to be a problem in modern browser which we use intersection observer
```
in-out: New element transitions in first, then when complete, the current element transitions out.
```

🐛 Fix ContentCard not triggered in non-observer lazyload

---

src/util/SwiperDirectives.js

I am seeing some 
```
TypeError: a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(bc)', 'a[b].target.className.indexOf' is undefined)
--
```
error from sentry, mainly from ios chrome
not sure if some swiper function would be broken by this PR though

🐛 Try to mitigate error in ios

---

functions/package.json
src/package-lock.json
src/package.json
src/pages/civic/index.vue
src/plugins/geoip.server.js
src/server/api/routes/civic/index.js
src/store/modules/ui.js

Change detection flag as non HK since it's the default behaviour and added browser language detection to have more accuracy

Fix payment selection for non HK user

---

src/components/CivicSubscriptionView/CivicSubscriptionView.vue

To prevent duplicate state change events

🐛 Guard civic view change event when state didn't change

---

src/components/CivicSettingsV1.vue
src/locales/en.json
src/locales/zh-Hant.json
src/pages/settings/civic.vue
src/pages/settings/payment/stripe/billing.vue
src/server/api/routes/civic/stripe.js
src/store/modules/getters/user.js

- Add a page that directly links to stripe billing page so that we can set this url in url/customer support message
- Allow expired user to enter civic setting page (which default to show v1) so that that won't be in an infinite loop in civic pages
- Show a message if we detect the user is `past_due` instead of `cancel` or no subscription, so that billing method can be updated
Known issue:
- Would show v1 option page even for v2 user
- After updating billing method, invoice payment retry is not auto triggered. We still won't treat v2 user as v2 user, and they cannot enter v2 panel until a payment retry is triggered and success

🐛 Allow civic liker in past_due or grace period to enter civic setting page

---

src/layouts/error.vue

e.g. https://rinkeby.liker.land/nft/iscn/iscn%3A%2F%2Flikecoin-chain%2FDmrE9fnxW-07v7rYLzuJwN73qfNRlhyrJIL5MdAPOIY

💩 Mitigate ISCN ID double decoding in path on firebase functions

---

src/components/EventModal/Collect/index.vue

💄 Fix disabled payment method button style

---

functions/package-lock.json
functions/package.json
src/nuxt.config.js
src/package-lock.json
src/package.json

Before:
After:
One potential issue is there was a mix of bn.js 4.x and 5.x, by reading changelog I don't see any breaking change, but we need some time to test

⚡️ Use one instance of bn.js

---

src/store/modules/actions/staticData.js
src/store/modules/actions/wallet.js
src/util/nft.js

The code split avoids loading @cosmjs thus the huge `libsodium` in front page for new users
Thus removing a few seconds js parsing block on main thread
Pre:
Post:

⚡️ Lazy load iscn and wallet library

---

src/components/NFTCampaign/Item.vue
src/constant/index.js

Ref: https://github.com/hilongjw/vue-lazyload/blob/6c4c3e5108bf89b5c71842ab8fb191fd0f06aa4e/src/lazy-component.js#L12-L14
I couldn't reproduce the UI glitch but I think the reason is `<lazy-component/>` always renders an empty child at the beginning which gives zero height at the initial rendering, hence all items will be triggered `show` event

Add back lazy load for campaign items

---

src/components/NFTPortfolio/Base.vue
src/components/NFTPortfolio/Item.vue
src/pages/nft/class/_classId/index.vue

Because the price's API takes a longer time to respond, in the first render, the component does not count the height of the price button, which causes the problem of overlapping cards.
the first render:
then get the price:

🐛 Fix NFT cards overlapping

---

src/mixins/portfolio.js

I am not sure if the extra call without await in the end is intentional though, seems most cases we call this on `mount` in other page
(But even if it's intentional it should not be written in this way)

⚡️ Remove duplicated call to fetch NFT list

---

src/components/Identity/Identity.avatar.vue

Now [user api](https://api.like.co/users/id/ckxpress/min) would return avatar in format like `https://api.like.co/users/id/ckxpress/avatar?size=400`, where we can define `size`
We can use properly sized image for display by replacing querystring

⚡️ Use resized avatar url

---

src/mixins/nft.js
src/store/modules/nft.js

- metadata are stored as `metadata.metadata` instead of  spreading to `metadata`
- handle iscn_owner not exists when uri is defined
- handle account type nft
- display nft image with ar:// and ipfs://

🐛 Fix nft chain metadata was not properly parsed

---

src/util/api/index.js

setting `ignore_to_list=` makes mint_nft / create_class etc goes away unexpectedly
Example:
https://node.testnet.like.co/likechain/likenft/v1/event?class_id=likenft1h5rx36c4f9aex6zsjl9dftn8qmglnjvpq88jdj3e2lwdgzz9m4nql0xkc8&nft_id=nft-02e8dd6a-999d-48f8-8add-02da61f433a7&action_type=%2Fcosmos.nft.v1beta1.MsgSend&action_type=mint_nft&action_type=new_class&ignore_to_list=&limit=100
vs
https://node.testnet.like.co/likechain/likenft/v1/event?class_id=likenft1h5rx36c4f9aex6zsjl9dftn8qmglnjvpq88jdj3e2lwdgzz9m4nql0xkc8&nft_id=nft-02e8dd6a-999d-48f8-8add-02da61f433a7&action_type=%2Fcosmos.nft.v1beta1.MsgSend&action_type=mint_nft&action_type=new_class&limit=100

🐛 Fix tx without receiver is filtered for pnft

---

src/components/NFTPortfolio/Base.vue
src/store/modules/nft.js
src/util/api/index.js
src/util/nft.js

Replace /sell API from like.co with indexer nft classes api
This allow listing of non-writing nft classes created/owned by user to be shown
This also automatically solves the issue of updating ISCN ownership (but a bug in indexer still exists that affects iscn with multiple updated versions)

♻️ Replace Selling API with NFT Class owner API

---

src/mixins/nft.js

The original computed prop `isWritingNFT` was refactored and populated from `nftClassCollectionMixin` in https://github.com/likecoin/liker-land/pull/790.
The properties should be renamed to `nftIsWritingNFT` accordingly.

🐛 Update computed prop name

---

src/components/NFTCover.vue
src/components/NFTPage/PreviewCard.vue
src/components/NFTPortfolio/Base.vue
src/components/NFTWidget/ContentPreview.vue

✨ Handle cover for different aspect ratios

---

src/components/EventModal/Transfer.vue

💄 [Transfer] Show displayName instead of address

---

src/pages/_id/index.vue

As the form now appears on all tabs, it is weird to show hint for no created NFT if the tab has nothing
E.g. Have  collected NFT but no created NFT

🩹 [Portfolio] Hide empty text in creator follow form

---

src/components/CivicLikerV3/Dashboard.vue
src/components/CivicLikerV3/Page.vue

⚡️ Prevent layout shifting after loading in civic dashboard

---

src/pages/_id/index.vue

design comment: portfolio gem list should be kept static (collected gems) to avoid confusion

💄 Only show collected gem list in portfolio

---

src/components/NFTAboutPage/FAQItem.vue

Using `v-if` hides the answer from HTML unless clicked on, which makes it uncrawlable
Using `v-show` allows the content to still exists in HTML while having same UX

🔍️ Use v-show instead of v-if for FAQ

---

src/components/NFTAboutPage/index.vue

The svg animation is larger in zh version, which blocks the whole CTA button
It's still partly blocked in this PR, not sure how to style it better
Related: https://github.com/likecoin/liker-land/issues/932

🐛 Fix NFT about page CTA is blocked

---

src/pages/_id/index.vue

refactoring error, `this.type` does not exists in parent

🐛 Fix undefined type

---

src/pages/notifications/index.vue
src/store/modules/wallet.js

- Fetch followee before displaying the notification count. (signLogin)
- Re-fetch the followee list to update the event sender. (handleRefresh)

👽 Fetch followee API bafore getEvents

---

src/util/api/index.js

These two APIs don't use `reverse` flag by the way.

👽️ Update qs of top fans and favorite creators APIs

---

src/store/modules/wallet.js

It appears that the inability of users to log in to liker.land using the Liker Land app is due to this reason.

🐛 Fix some signers not provide sign method

---

src/store/modules/nft.js

Found a case which the URI refers to a GIF file, then axios converted the data into a looooooong string (length = `9475978`), which is then assigned to `apiMetadata`, causing OOM in object spread operations and `Vue.set` (or further processing from other computed / watched logics, not sure)

🐛 Guard metadata fetched from URI

---

src/nuxt.config.js

Desired behaviour:
- go to browser locale for any non-prefix path
- do not enable cookie since firebase function restriction
- use user selected locale (from api) if one is set

🌐 Always redirect to browser local for no prefix path

---

src/server/api/routes/users/v2/auth.js
src/server/api/util/cosmos.js
src/store/modules/wallet.js
src/util/cosmos.js

This is a hotfix, regular fix ("the right way") needs support of `signArbitrary` from `@likecoin/wallet-connector`.
Tested for Keplr (memo) and Cosmostation (ADR-036), both on browser extensions.

🚑️ Use ADR-036 for login signing for Cosmostation

---

src/components/NFTPage/Recommendation.vue
src/components/NFTPortfolio/Item.vue
src/mixins/nft.js
src/mixins/portfolio.js
src/store/modules/nft.js

The current recommendation list requires fetching all NFT classes created or collected by the creator, which results in retrieving all corresponding details that lead to an excessive number of API calls. This is also the reason why the creator's information failed to be fetched sometimes.
The fix is to fetch only the necessary recommendation items when they become visible on the screen.

⚡️ Lazy fetch details for recommendation list

---

src/store/modules/nft.js
src/util/nft.js

afaik:
- chain api support dual prefix query natively
- indexer api support dual prefix long time ago, some time after frontend patch was applied
so no reason for frontend to query dual prefix now, we would save 50% api calls here

⚡️ Remove dual prefix fetch

---

src/components/NFTBook/EditionCompareTableColumn.vue
src/components/NFTBook/EditionCover.vue
src/components/NFTEditionSelect.vue
src/locales/en.json
src/locales/zh-Hant.json
src/mixins/nft.js
src/pages/nft/class/_classId/index.vue
src/store/modules/nft.js

https://github.com/likecoin/liker-land/assets/75730405/b6df20d3-0230-4893-aff2-c65606c8c151

💄 [_classId/] Add <NFTBookEditionCover/>

---

src/components/EventModal/Collect/index.vue
src/components/TxModal.vue
src/constant/index.js
src/locales/en.json
src/locales/zh-Hant.json
src/mixins/nft.js
src/pages/nft/fiat/stripe.vue

Allow closing collect modal during processing to allow quicker purchase/ reduce blocking
Shows close button after grant tx is posted to prevent spend limit grant from overlapping
Update:
Add alert prompt for closed modal results
Known possible issue:
Keep collecting a same class ID might make collect modal act funny, since current active checking is `modal classId === collected classId`

🚸 Allow closing collect modal after grant tx is posted

---

public_base/.well-known/apple-app-site-association
public_base/.well-known/assetlinks.json

The plan is to use `/getapp` as entrance for walletconnect and other deeplink action
e.g. https://liker.land/getapp?action=wc&uri=xxx

🔧 Add wellknown for `/getapp` deeplink

---

src/components/NFTBook/ItemCard.vue

NFTCover would fill the image with placeholder if src not set
Now the placeholder only appears after nft metadata is loaded

💄 Do not hide placeholder if book nft img src not set

---

src/components/NFTSupply/Table.vue

🐛 Fix cropped supply table in home page

---

src/components/NFTCover.vue

It seems that `v-bind` not support class name object

🐛 Fix `<NFTCover/>` class name

---

src/pages/notifications/index.vue
src/store/modules/wallet.js

Notifications events are loaded whenever user is logged in or load likerland with a session
Now this is causing huge performance issue for user with loads of notifcations since all NFT metadata are fetched whenever a likerland page is opened

⚡️ Do not load notification details on login

---

src/components/NFTPage/ChainDataSection/index.vue
src/components/NFTPage/CollectorList/index.vue
src/components/ShowMore.vue
src/mixins/nft.js
src/pages/nft/class/_classId/_nftId.vue
src/pages/nft/class/_classId/_nftId/message.vue
src/pages/nft/class/_classId/index.vue

**Before**
https://github.com/likecoin/liker-land/assets/75730405/31e7a37c-75ac-41b1-92ff-c55f5496df5f
**After**
https://github.com/likecoin/liker-land/assets/75730405/f7e70de2-dec8-435f-8de2-70f72175c5bd

⚡️ [_classId/] Lazy load userInfo for collectorList & history

---

src/mixins/nft.js

https://liker.land/zh-Hant/nft/class/likenft1uvcrlem98cquja0lly8jdyum3cw7glyw2ujpzl4ap5u9ah9eapzq0vxhad
iscnOwner is undefined now somehow

🚑️ Fix missing owner info in class page

---

src/components/NFTBook/ItemCard.vue

[TAS-191] 🩹 Fix duplicated content types for NFT Book

---

src/components/NFTPage/ChainDataSection/Metadata.vue

Before 
After
Remains a button if no duplicated type

[TAS-191] 🚸 Fix duplicated type of content fingerprints in metadata UI

---

src/components/NFTPage/ChainDataSection/Metadata.vue

[TAS-191] 📱 Fix overflow content fingerprints in mobile

---

src/components/NFTViewOptionList.vue
src/mixins/nft.js

Currently, if there is no `external_url`, it will display the `iscnURL`. However, the metadata section will also have an iscnUrl btn, so I think it would be more intuitive to hide the "View Content" btn directly if there is no `external_url`.
current situation:

[TAS-115]💄 Hide "View Content" button if external_link is empty

---

src/pages/dashboard/index.vue

Liker Land app use `in_app=1` qs for hiding header and footer

[TAS-329] 🚑 Fix qs not passed through redirect

---

src/components/NFTViewOptionList.vue

Before
PDF URL display as 書訊
After
Detected URL with `.pdf`, shows `Open PDF`

[TAS-359] 🚸 Show "open PDF/EPUB" if URL has file extension

---

functions/package-lock.json
functions/package.json
src/experiments/index.js
src/experiments/recommend-connection-method.js
src/mixins/wallet-login.js
src/nuxt.config.js
src/package-lock.json
src/package.json
src/store/modules/wallet.js

[TAS-345] ⚗️ Test recommended connection method

---

src/components/NFTBook/ItemCard.vue

Since we have `whitespace-pre-line`, the line breaks in code are actually rendered out

🩹 Fix extra line break in NFT Book description

---

src/pages/civic/index.vue

some external links are still in the format of 
`https://liker.land/civic?from=ckxpress`

🚸 Redirect /civic?from=id to id page

---

src/layouts/default.vue
src/mixins/in-app.js
src/pages/store/index.vue
src/util/client.js

- Redirect `in_app` from `/store` to `/store/articles` in `fetch` to prevent triggering inapp mixin
- Only use `in_app` qs for likerland app detection in fetch to prevent SSR inconsistent
- Move inapp watchers to default layout so that we won't have 3 watcher triggering when 3 pages import inapp mixin

⚡️ Prevent multiple connect attempt to likerland inapp browser

---

functions/modules/liker.js
src/util/api/index.js
src/util/ui.js

The API originally used has [expired](https://github.com/orgs/dicebear/discussions/374). It has been updated to version [7.x](https://www.dicebear.com/styles/identicon/).

[TAS-919] 👽 Update avatar URL generation

---

src/pages/reader/epub.vue

Note: The TOC list utilizes the HTML or XHTML filenames of chapters as its keys. 
However, to navigate to a specific chapter, the `rendition.display` function requires the full path of the file. 
It's important to acknowledge that the folder structure within a zipped EPUB may vary from one file to another. 
The file paths could differ when dealing with different EPUB files.

🐛 Fix incorrect chapter path

---

src/components/AuthRequiredView.vue
src/store/modules/wallet.js

In auth view, reuse current wallet connect method instead of re-initing whole select connect method flow

🚸 Do not reinit wallet in sign login

---

src/components/NFTPortfolio/MainView.vue

I think this issue occurred because I reduced the width in the previous PR
[💄 Add recommendation section to the empty portfolio page](https://github.com/likecoin/liker-land/pull/1529/commits/1071487aba931900045f00679f7e4b45b1f8512e#diff-1ecbb852d58b0749ca3f53a4e6e3380fcc0100dfee87ecb64004d8213f786b3fR133)
fix now

[TAS-1231] 🐛 Fix item wrapping issue due to insufficient width

---

src/components/NFTCover.vue

turns out webpack cannot handle ternary operation in this case

🐛 Fix broken default nft and collection image

---

src/components/NFTPortfolio/MainView.vue
src/mixins/nft.js

- `NFTPortfolio/MainView.vue` contains many nft class instead of 1 nft class, but nft mixin expect an nft class id as it's root of data source
- We can't call `fetchRecommendInfo` from here, `iscnOwner` is undefined
- Somehow `portfolioItemsTrimmed` is modified if we call `fetchRecommendInfo` under these condition causing `fetchRecommendInfo` goes into an infinite loop
For a very quick fix, we should just not call `fetchRecommendInfo` from here, and maybe figure out why `portfolioItemsTrimmed` is modified and call `this.fetchCollectedNFTClassesByAddress(this.getAddress)` in a later PR

🐛 Do not use nft mixin in non nft class component

---

src/components/NFTCover.vue

Often the whole NFT card component is lazyloaded, setting lazy in  just mess up the image src http request priority

⚡️ Remove lazy in <img> for nft cover

---

src/components/NFTBook/GiftDialog.vue
src/pages/nft/class/_classId/index.vue

- Remove unused props in GiftDialog
- Avoid using undefined as the selected value

🐛 Fix selected value undefined

---

src/mixins/nft-collection.js

`formattedNFTPriceInUSD()` is used in `_collectionId` page but is not defined in collection mixin

[TAS-1551] 💩 Fix missing formattedNFTPriceInUSD in collection page

---

src/assets/css/_global.scss
src/nuxt.config.js
src/tailwind.config.js

- Tailwind will apply `font-sans` style to `<html>`, so we don't need to specify `font-sans` class to `<html>`
- the stylesheet of Tailwind (Newer version) from `likecoin-wallet-connector` is overriding some font styles, but it doesn't matter for now
---
I just keep Proxima Nova for English since Typekit doesn't allow zero font

[TAS-1433] ⚡️ Add fallback fonts after removing fonts from Typekit

---

src/pages/reader/pdf.vue

Combines with:
https://github.com/likecoin/pdf.js/pull/4
https://github.com/likecoin/pdf.js/pull/5

[TAS-1568] ⚡️ Use cache API and postMessage for pdf books

---

src/components/NFTBook/Cover.vue
src/pages/nft/claim/index.vue

[TAS-1786] 🩹 Fix cover height for Safari

---

src/pages/reader/epub.vue

as a safe guard to prevent `renderTo` call randomly querying id from across lifecycles

🎨 Use ref instead of id to define epub viewer

---

src/pages/index.vue

A layout change from a hydration mismatch page would cause double mount event

[TAS-1790] 🐛 Fix hydration mismatch caused by html comment

---

src/pages/reader/epub.vue

💄 Fix loading indicator behind book bind

---

src/pages/reader/epub.vue

Seems viewer's width affects images' height, removing width limit to viewer can mitigate the spacing issue
Before
After

💄 Remove epub reader width limit

---

src/components/NFTEditionSelect.vue

[TAS-2107] 🐛 Fix default selected edition might be out of stock

---

src/components/NFTViewOptionList.vue

[TAS-2131] 🐛 Fix view content dropdown option name

---

src/pages/nft/claim/index.vue

In `data()`, `walletEmail` is `undefined`
https://github.com/likecoin/liker-land/blob/52a1737950ede7fd19de0ffe139e35f2002eadd4/src/pages/nft/claim/index.vue#L548-L559

[TAS-2134] 🐛 Fix email is empty in free purchase

---

src/tailwind.config.js

STHeiti don't have support font-weight
Before
After

💄 Remove STHeiti font

---

src/components/NFTPage/Recommendation.vue

Not sure why `classId` can be undefined when it seems to be used everywhere in this function

🚑️ Guard undefined classId in recommend list filter

---

src/components/EventModal/Collect/index.vue
src/components/ShoppingCart/ListRow.vue
src/mixins/nft-collection.js
src/mixins/nft-or-collection.js
src/mixins/nft.js
src/pages/nft/class/_classId/index.vue
src/pages/nft/collection/_collectionId/index.vue
src/pages/shopping-cart/book.vue
src/store/modules/cart.js
src/store/modules/nft.js
src/util/api/index.js

Require: https://github.com/likecoin/likecoin-api-public/pull/768

[TAS-2273] 🔥 Remove book payment price api calls

---

src/mixins/nft.js
src/pages/nft/class/_classId/_nftId.vue
src/pages/nft/class/_classId/index.vue
src/pages/nft/collection/_collectionId/index.vue

Since facebook cannot parse json-ld with multiple `@type` like google does, and also likely does not support product variant in a same page, we set the current edition product info in og
https://developers.facebook.com/docs/marketing-api/catalog/reference/#og-tags

[TAS-2413] 📈 Set product data for 1st edition in og meta for fb

---

src/components/NFTBook/ItemCard.vue
src/components/NFTBook/ItemCardV2.vue
src/components/NFTCollection/ItemCard.vue
src/locales/en.json
src/locales/zh-Hant.json

[TAS-2320] 🚸 Add loading placeholder for <itemCard/>

---

src/components/NFTPortfolio/Item.vue
src/components/NFTPortfolio/MainView.vue
src/store/modules/nft.js

[TAS-2340] 🐛 Enable content viewing using ownedNFTId instead of lastOwnedNFTId

---

src/components/NFTBook/Cover.vue
src/components/NFTBook/ItemCard.vue
src/components/NFTBook/SpecTableItemAccessMethod.vue
src/components/NFTBook/SpecTableItemAvailableFormat.vue
src/components/NFTBook/SpecTableItemDateReleased.vue
src/components/NFTBook/SpecTableValue.vue

[TAS-2544] 💄 Fix product page UI

---

src/locales/en.json
src/locales/zh-Hant.json
src/pages/nft/claim/index.vue

[TAS-2568]🐛 Fix login issue on claimed book pages

---

src/pages/reader/pdf.vue

listen event from https://github.com/likecoin/pdf.js/pull/10

[TAS-2787] 📈 Add logging for PDF download event

---

src/components/SearchBar.vue

https://github.com/user-attachments/assets/208a677c-b3c8-4965-9264-eeae487ffdb6

[TAS-3080] 🚸 Enhance search behavior

---

src/mixins/utm.js

if it has srs it should be organic without any extra utm params
https://support.google.com/analytics/answer/11479699?hl=en

📈 Manually attribute google organic if srsltid qs is set
